### ISSUE TITLE
Plans on implementing Nuxt-fontaine?

### ISSUE THREAD

**Issue by StevenJPx2** [ivodolenc/nuxt-font-loader#12]
### Request Description

[Nuxt Fontaine](https://github.com/nuxt-modules/fontaine) is a cool library that'll help with page load speeds by default by doing some magic with font metrics. It'll be cool if this library has it by default.

### Alternative Solutions

None.

**Comment by ivodolenc** [comment]
Hi, thanks for the suggestion.

This module already uses methods for best performance when it comes to font loading.

The module automatically detects the configuration, depending on the strategy whether it is `local` or `external`, and adds _preconnect_ and _preload_ link tags in the _head_ section with minified inline styles for the `@font-face` rules.

This is all done by the minimal footprint so there is no additional code bloat. The module has only one dependency (for styling console logs) which is also under 1kb.

I just did some quick tests and here are the results:

<img width="516" alt="Screen Shot 2022-11-30 at 11 44 14" src="https://user-images.githubusercontent.com/51852491/204779414-4757c4e5-34b1-49a4-847f-3144a0389849.png">

<img width="744" alt="Screen Shot 2022-11-30 at 11 43 42" src="https://user-images.githubusercontent.com/51852491/204779462-8f6e35bc-9175-4fc7-8e21-83582b0d97ef.png">

#### Test environment

1. Default [nuxt-app](https://nuxt.com/docs/getting-started/installation#new-project) project
2. `nuxt-font-loader` with the `local` strategy

```js
// nuxt.config.ts

{
  modules: ['nuxt-font-loader'],

  fontLoader: {
    local: [
      {
        src: '/fonts/AspektaVF.woff2',
        family: 'Aspekta Variable',
        weight: '100 900'
      }
    ]
  }
}
```

3. Run `generate` and `preview` commands

So, in terms of page load speed, that's pretty much it.

As for your suggestion, I don't plan to implement it right now, I want to keep the module simple.

But just out of curiosity, have you had any performance or page load issues with this module?
