### ISSUE TITLE
Can add support for unicode-range?

### ISSUE THREAD

**Issue by helenmoon1** [ivodolenc/nuxt-font-loader#18]
### Request Description

The unicode-range CSS descriptor sets the specific range of characters to be used from a font defined by [@font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) and made available for use on the current page. If the page doesn't use any character in this range, the font is not downloaded; if it uses at least one, the whole font is downloaded.

### Alternative Solutions

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range

**Comment by ivodolenc** [comment]
Hi, nice one, thanks for the suggestion 👍

I'm labeling this as _planned_ as it will be a nice addition to the module.

As soon as I find some time, I'll start working on it.

**Comment by ivodolenc** [comment]
New options have been added in the latest version `2.3.0`.

Feel free to test them. Cheers 👋🏻
