### ISSUE TITLE
Font loading but console error

### ISSUE THREAD

**Issue by Joaojack** [ivodolenc/nuxt-font-loader#6]
Hi, I'm using an adobe typekit font with your module. The website is generated static and everything works fine, the font is displayed, although i have this error in console : 
`GET https://use.typekit.net/[myprojectcode].css/ net::ERR_ABORTED 404`

My config settings : 
`  fontLoader: {
    url: 'https://use.typekit.net/[myprojectcode].css/',
    prefetch: true,
    preconnect: true
  },`
Do you know why this error pos in my console ?
thanks

**Comment by ivodolenc** [comment]
Hi, it's hard to say exactly where the problem is without inspecting the code. 

> My config settings :
> `fontLoader: { url: 'https://use.typekit.net/[myprojectcode].css/', prefetch: true, preconnect: true },`

Double check that the link to the styles is correct. (try to remove `/` after `'...css/'`)

**Comment by Joaojack** [comment]
Well...you solved the issue, it was the slash. I didn't pay attention as Adobe provides the link with it. Thanks a lot !

**Comment by ivodolenc** [comment]
Np, I'm glad it worked! Cheers!
